r"""The non-congruence door, part 1 (2026-09-29): group theory, exact.

A.  -I in <T, L_w> mod 2^a ?   The G-part of any family with bounded denominators is congruence (Calegari-Dimitrov-Tang)
    and carries chi_-4 at the prime 2, on which -I acts by -1 (odd weight).  A multiplier trivial on T and L_w must then
    kill it whenever -I lies in the group generated by T and L_w modulo 2^a.
B.  The smallest groups with harmless pair (infinity: width 1, 0: width w in {5, 6, 7}): transitive pairs (s, u), s^2 = u^3 = 1,
    t = s then u (T = SU), genus 0, three cusps.  Index 9 (one elliptic point of order 2) and index 10 (one of order 3).
    Condition: the base point is fixed by t (width 1) and s(base) lies in a t-cycle of length w (the cusp 0 = S(oo)).
    Reported: cusp widths, elliptic points, |<s,u>| against |PSL2(Z/N)| (N = lcm of widths; a group of order not dividing it
    is non-congruence), and the count of distinct subgroups.
Usage: python door_groups.py"""
import itertools, math
from collections import deque

print("A. Is -I in <T, L_w> inside SL2(Z/2^a)?")
def mul(A, B, m):
    return ((A[0]*B[0] + A[1]*B[2]) % m, (A[0]*B[1] + A[1]*B[3]) % m, (A[2]*B[0] + A[3]*B[2]) % m, (A[2]*B[1] + A[3]*B[3]) % m)
def gen_group(gens, m):
    I = (1, 0, 0, 1); seen = {I}; dq = deque([I])
    while dq:
        x = dq.popleft()
        for g in gens:
            y = mul(x, g, m)
            if y not in seen: seen.add(y); dq.append(y)
    return seen
for a in (2, 3, 4, 5, 6):
    m = 2**a; minusI = (m - 1, 0, 0, m - 1)
    row = []
    for w in range(1, 17):
        G = gen_group([(1, 1, 0, 1), (1, 0, w % m, 1)], m)
        row.append("%d%s" % (w, "+" if minusI in G else "."))
    print("   mod 2^%d: %s" % (a, " ".join(row)))
print("   (+ : -I lies in the group; . : it does not)")

print("\nB. Smallest non-congruence candidates")
def cycles(p):
    n = len(p); seen = [False]*n; out = []
    for i in range(n):
        if not seen[i]:
            c = []; j = i
            while not seen[j]: seen[j] = True; c.append(j); j = p[j]
            out.append(c)
    return out
def compose(p, q):            # first p, then q
    return tuple(q[p[i]] for i in range(len(p)))
def involutions(n, fixed):
    pts = list(range(n))
    def rec(rem):
        if not rem: yield {}; return
        x = rem[0]
        # x fixed
        yield from ({**d, x: x} for d in rec(rem[1:]))
        for y in rem[1:]:
            rest = [z for z in rem[1:] if z != y]
            for d in rec(rest): yield {**d, x: y, y: x}
    for d in rec(pts):
        if sum(1 for k, v in d.items() if k == v) == fixed:
            yield tuple(d[i] for i in range(n))
def group_order(gens, n):
    I = tuple(range(n)); seen = {I}; dq = deque([I])
    while dq:
        x = dq.popleft()
        for g in gens:
            y = compose(x, g)
            if y not in seen: seen.add(y); dq.append(y)
    return len(seen)
def psl2_order(N):
    o = N**3
    for p in set(f for f in range(2, N + 1) if N % f == 0 and all(f % d for d in range(2, f))):
        o = o*(p*p - 1)//(p*p)
    return o//2 if N > 2 else o
def canon(s, u, base):
    lab = {base: 0}; order = [base]; dq = deque([base])
    while dq:
        x = dq.popleft()
        for g in (s, u):
            y = g[x]
            if y not in lab: lab[y] = len(order); order.append(y); dq.append(y)
    n = len(s)
    return (tuple(lab[s[order[i]]] for i in range(n)), tuple(lab[u[order[i]]] for i in range(n)))
for mu, e2, e3 in ((9, 1, 0), (10, 0, 1)):
    ucyc = [(0, 1, 2), (3, 4, 5), (6, 7, 8)]
    u = list(range(mu))
    for (x, y, z) in ucyc: u[x], u[y], u[z] = y, z, x
    u = tuple(u)
    found = {}
    for s in involutions(mu, e2):
        t = compose(s, u)
        cyc = cycles(t)
        if len(cyc) != 3: continue
        # transitivity
        comp = {0}; dq = deque([0])
        while dq:
            x = dq.popleft()
            for g in (s, u):
                if g[x] not in comp: comp.add(g[x]); dq.append(g[x])
        if len(comp) != mu: continue
        clen = {x: len(c) for c in cyc for x in c}
        widths = tuple(sorted(len(c) for c in cyc))
        for base in range(mu):
            if clen[base] != 1: continue
            w0 = clen[s[base]]
            if s[base] == base or w0 not in (5, 6, 7): continue
            key = canon(s, u, base)
            if key not in found:
                found[key] = (widths, w0)
    print("   index %d (e2 = %d, e3 = %d): %d subgroups with a width-1 cusp oo and width 5/6/7 at 0" % (mu, e2, e3, len(found)))
    for key, (widths, w0) in sorted(found.items(), key=lambda kv: kv[1]):
        s, u2 = key
        N = 1
        for wdt in widths: N = N*wdt//math.gcd(N, wdt)
        go = group_order([s, u2], mu)
        po = psl2_order(N)
        print("     widths %s, w(0) = %d, level N = %d, |<s,u>| = %d, |PSL2(Z/N)| = %d  -> %s"
              % (widths, w0, N, go, po, "non-congruence" if po % go else "order divides (test further)"))
        print("        s = %s  u = %s" % (s, u2))
